### ISSUE TITLE
Rosbags are empty

### ISSUE THREAD

**Issue by telemething** [gaia-platform/rosbag2_snapshot#4]
Rosbags are created but are empty. ros2 bag status shows count = 0 and all files are always the same size, yaml = 338 and db =16.4k.

Confirmed topics exist and messages are flowing. [rosbar2_storage] messages on console show subscription to /image and /scan topics, and then indicate successful triggers but show /image and /scan not subscribed.

**Comment by JWhitleyWork** [comment]
@telemething If this is still happening and you are using a memory limit, check out #8 for a fix. If not, please verify whether or not this is still occurring.

**Comment by JWhitleyWork** [comment]
Much appreciated! #8 has been merged and I'll close this issue.

**Comment by JWhitleyWork** [comment]
Sorry, replied to the wrong one. See #6 for the fix.
